# Generated by Django 5.2.3 on 2025-07-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="currency",
            table="currency",
        ),
        migrations.AlterModelTable(
            name="exchangerate",
            table="exchange_rate",
        ),
    ]
